services:
  - type: web
    name: voice2order
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OAUTH_SERVER_URL
        value: https://api.manus.im
      - key: VITE_OAUTH_PORTAL_URL
        value: https://auth.manus.im
      - key: VITE_APP_TITLE
        value: Voice2Order
      - key: BUILT_IN_FORGE_API_URL
        value: https://api.manus.im

